package ru.manakin.aucmonitor.model;

public enum SubcategoryEnum {
    // Артефакты
    BIOCHEMICAL, ELECTROPHYSICAL, GRAVITY, THERMAL, OTHER_ARTS,
    // Броня
    CLOTHES, COMBAT, COMBINED, DEVICE, SCIENTIST,

    // Обвесы
    ACCESSORY, BARREL, COLLIMATOR_SIGHTS, FOREND, MAG, PISTOL_HANDLE, OTHER,
    // Оружие
    ASSAULT_RIFLE, HEAVY, MACHINE_GUN, MELEE, PISTOL, SHOTGUN_RIFLE, SNIPER_RIFLE, SUBMACHINE_GUN
}
